POST http://localhost:3000/campaigns

{
    "name": "change",
    "content": "chage password",
    "emails": ["jo@teste.com", "paula@gmail.com", "lucas@gmail.com"]
}

###
GET http://localhost:3000/campaigns/d96dpidlv9v5movoi5rg

###
DELETE http://localhost:3000/campaigns/delete/d96e62dlv9v7893nsg0g
