POST http://localhost:3000/campaigns

{
    "name": "change",
    "content": "chage password",
    "emails": ["luis@teste.com.br"]
}

###
GET http://localhost:3000/campaigns/

### 
PATCH http://localhost:3000/campaigns/cancel
