###
GET http://localhost:3000/campaigns/lvsxTLIDZHoUgXLDQQR2YbujiPrUAZP7VtGFBObq7AI

###
DELETE http://localhost:3000/campaigns/delete/d96dpidlv9v5movoi4rg

### GET_TOKEN
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailcampaign&client_secret=suv0pl09TPTD0vYk1hyXyOZoZIeJkKaw&username=agenciamartinidigital@gmail.com&password=123456&grant_type=password

###
POST http://localhost:3000/campaigns
Authorization: Bearer {{GET_TOKEN.response.body.$.access_token}}
Content-Type: application/json

{
    "Name": "change",
    "Content": "change password",
    "emails": ["luis@teste.com", "jo@teste.com"]
}
